---
version: '3'
services:

  duckling:
    image: rasa/duckling:latest
    restart: unless-stopped
    container_name: duckling
    expose:
      - "8000"

  rasa:
    image: weatherbot.azurecr.io/weatherbot/rasa
    restart: unless-stopped
    container_name: rasa
    ports:
    - "5005:5005"
    expose:
      - "5005"
    depends_on:
      - duckling

  weatherchat:
    image: weatherbot.azurecr.io/weatherbot/weatherchat
    restart: unless-stopped
    container_name: weatherchat
    expose:
      - "8443"
    environment:
      SPRING_PROFILES_ACTIVE: local-docker
    volumes:
      - ./volumes/certbot/conf/live/weatherbotwebtec.westus3.cloudapp.azure.com:/app/ssl
    depends_on:
      - rasa

  weatherchatfrontend:
    image: weatherbot.azurecr.io/weatherbot/weatherchatfrontend
    restart: unless-stopped
    container_name: weatherchatfrontend
    environment:
      DOMAIN_NAME_HTTPS: weatherbotwebtec.westus3.cloudapp.azure.com
      DOMAIN_NAME_HTTP: weatherbotwebtec.westus3.cloudapp.azure.com
    volumes:
      - ./volumes/nginx:/etc/nginx/templates:rw,cached
      - ./volumes/certbot/conf:/etc/nginx/ssl/:ro
      - ./volumes/certbot/www:/var/www/certbot:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - weatherchat

  certbot:
    image: certbot/certbot:latest
    restart: unless-stopped
    container_name: certbot
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt:rw
      - ./volumes/certbot/www:/var/www/certbot:rw
    entrypoint: >
      /bin/sh -c ' \
          trap exit TERM; \
          while :; do \
          certbot renew; \
          openssl pkcs12 -export \
              -in /certs/fullchain.pem \
              -inkey /certs/your_privkey.pem \
              -out /etc/letsencrypt/keystore.p12 \
              -password pass:Backend; \
          sleep 12h & wait $${!}; \
      done;'

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    restart: unless-stopped
    container_name: exporter
    command: [ "-nginx.scrape-uri=http://weatherchatfrontend:9876/metrics" ]
    expose:
      - "9113"
    depends_on:
      - weatherchatfrontend

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    volumes:
      - ./volumes/prometheus:/etc/prometheus/:ro
    expose:
      - "9090"

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    ports:
      - "3000:3000"
    user: "$UID:$GID"
    volumes:
      - ./volumes/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./volumes/grafana/grafana-data:/var/lib/grafana
