global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring boot weatherchat'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['weatherchat:9875']

  - job_name: 'nginx weatherchatfrontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['exporter:9113']
